apiVersion: apps/v1
kind: Deployment
metadata:
  name: perissinotto-bank-backend
  namespace: dev-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perissinotto-bank-backend
  template:
    metadata:
      labels:
        app: perissinotto-bank-backend
    spec:
      containers:
        - name: backend
          image: aperissinotto/perissinotto-bank-backend:latest
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-secret
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: perissinotto-bank-backend
  namespace: dev-apps
spec:
  selector:
    app: perissinotto-bank-backend
  ports:
    - port: 80
      targetPort: 8080
