apiVersion: apps/v1
kind: Deployment
metadata:
  name: perissinotto-bank-frontend
  namespace: dev-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perissinotto-bank-frontend
  template:
    metadata:
      labels:
        app: perissinotto-bank-frontend
    spec:
      containers:
        - name: frontend
          image: aperissinotto/perissinotto-bank-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: perissinotto-bank-frontend
  namespace: dev-apps
spec:
  selector:
    app: perissinotto-bank-frontend
  ports:
    - name: http
      port: 80         # porta do Service
      targetPort: 80   # porta do container
  type: ClusterIP
