name: Build Docker Images for ARM64

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      # Login no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ============================
      # Build & Push Backend ARM64
      # ============================
      - name: Build & Push Backend ARM64
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/perissinotto-bank-backend:latest \
            ./backend \
            --push

      # ============================
      # Build & Push Frontend ARM64
      # ============================
      - name: Build & Push Frontend ARM64
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/perissinotto-bank-frontend:latest \
            ./frontend \
            --push