name: Build Docker Images for ARM64

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      # Configura Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build e push backend ARM64
      - name: Build & Push Backend ARM64
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/perissinotto-bank-backend:latest \
            ./backend \
            --push

      # Build e push frontend ARM64
      - name: Build & Push Frontend ARM64
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/perissinotto-bank-frontend:latest \
            ./frontend \
            --push
